version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      '-s -w -X github.com/sbldevnet/{{ .ProjectName }}/cmd.version={{.Version}} -X github.com/sbldevnet/{{ .ProjectName }}/cmd.commit={{.Commit}}'

universal_binaries:
  - replace: true

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    format_overrides:
      - goos: linux
        formats:
          - tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: 'checksums.txt'

release:
  draft: true
